server.port: 8080
server.tomcat.max-threads: 0
server.tomcat.uri-encoding: UTF-8
server.servlet.context-path: /springboot #配置内置tomcat的 context-path
#--------------------配置spring jackson ------------------------------------------------

spring.jackson.date-format: yyyy-MM-dd HH:mm:ss#日期格式化
spring.jackson.time-zone: GMT+8#时区    
spring.jackson.serialization.indent_output: true #格式化输出



#-------------------spring.jpa 默认Hibernate5.0----------------------------------------------
spring.jpa.generate-ddl: false
#控制台显示sql打印
spring.jpa.show-sql: true 
#springboot 指定数据源 Druid
spring.datasource.type: com.alibaba.druid.pool.DruidDataSource
#-------------------spring.datasource mysql 单数据源----------------------------------------------


#spring.datasource.driverClassName: com.mysql.jdbc.Driver
#spring.datasource.url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&useSSL=true
#spring.datasource.username: root
#spring.datasource.password: e234567b
#spring.datasource.initialSize: 20
#spring.datasource.minIdle: 50
#spring.datasource.maxActive: 200
  
#-------------------spring.datasource  单数据源----------------------------------------------
#spring.datasource.driverClassName: oracle.jdbc.OracleDriver
#spring.datasource.url: jdbc:oracle:thin:@localhost:1521:test
#spring.datasource.username: root
#spring.datasource.password: e234567b
#spring.datasource.initialSize: 20
#spring.datasource.minIdle: 50
#spring.datasource.maxActive: 200
#-------------------------------------------------

#-------------------定义多数据源配置 db1 mysql----------------------------------------------
db1.datasource.driverClassName: com.mysql.jdbc.Driver
db1.datasource.url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&useSSL=true
db1.datasource.username: root
db1.datasource.password: e234567b
db1.datasource.initialSize: 20
db1.datasource.minIdle: 50
db1.datasource.maxActive: 200
  
#-------------------定义多数据源配置 db2 oracle----------------------------------------------
db2.datasource.spring.datasource: 
db2.datasource.driverClassName: oracle.jdbc.OracleDriver
db2.datasource.url: jdbc:oracle:thin:@localhost:1521:test
db2.datasource.username: root
db2.datasource.password: e234567b
db2.datasource.initialSize: 20
db2.datasource.minIdle: 50
db2.datasource.maxActive: 200


  
  
  
  