server.port: 8080
server.tomcat.max-threads: 0
server.tomcat.uri-encoding: UTF-8
server.servlet.context-path: /springboot #配置内置tomcat的 context-path
#--------------------配置spring jackson ------------------------------------------------

spring.jackson.date-format: yyyy-MM-dd HH:mm:ss#日期格式化
spring.jackson.time-zone: GMT+8#时区    
spring.jackson.serialization.indent_output: true #格式化输出



# ================================================
#                   Thymeleaf配置
# ================================================
# 是否启用thymeleaf模板解析
spring.thymeleaf.enabled: true
# 模板模式设置，默认为HTML5
spring.thymeleaf.mode: HTML 
# 模板的编码设置，默认UTF-8
spring.thymeleaf.encoding: UTF-8
# 模板的媒体类型设置，默认为text/html
spring.thymeleaf.servlet.content-type: text/html

# 是否开启模板缓存（建议：开发环境下设置为false，生产环境设置为true）
spring.thymeleaf.cache: false
  

##设置单个文件的大小
spring.servlet.multipart.max-file-size: -1 #10Mb 
#设置单次请求的文件的总大小
spring.servlet.multipart.max-request-size: -1 #100Mb 
  
#文件保存路径

files.path: E:\test 